---
ignore-from-file: [.gitignore]

extends: default

rules:
  document-start: disable
  float-values: enable
  line-length: disable
  octal-values: enable
  indentation:
    indent-sequences: consistent
  truthy:
    check-keys: false
